In [12]:
import numpy as np

In [ ]:
from src.models.custom_LinearRegression import LinearRegression

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("housing_cleaned.csv")

In [3]:
data.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,16.023785,8.699515,4,1,2,1,0,1,0,0,2,0,0.5
1,16.023785,8.794825,4,2,2,1,1,1,0,1,1,1,0.0
2,16.008281,9.047821,3,2,4,1,0,0,0,1,2,0,1.0
3,16.000438,8.433812,3,2,2,1,1,0,0,1,2,0,1.0
4,15.996493,8.767173,3,2,2,1,0,0,0,1,1,1,0.5

In [4]:
x = data.drop('price',axis =1)
y = data['price']

In [5]:
x.head()

,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,8.699515,4,1,2,1,0,1,0,0,2,0,0.5
1,8.794825,4,2,2,1,1,1,0,1,1,1,0.0
2,9.047821,3,2,4,1,0,0,0,1,2,0,1.0
3,8.433812,3,2,2,1,1,0,0,1,2,0,1.0
4,8.767173,3,2,2,1,0,0,0,1,1,1,0.5

In [6]:
y.head()

0    16.023785
1    16.023785
2    16.008281
3    16.000438
4    15.996493
Name: price, dtype: float64

In [13]:
from sklearn.model_selection import train_test_split

In [9]:
(x_train,x_test,y_train,y_test) = train_test_split(x,y,test_size = 0.4,random_state = 42)

In [ ]:
lr = LinearRegression()
lr.fit(x_train,y_train)

In [15]:
lr.intercept_

np.float64(12.18164898044276)

In [16]:
lr.coef_

array([0.28167966, 0.03693591, 0.1494704 , 0.0743033 , 0.1141373 ,
       0.08338239, 0.10628964, 0.11864355, 0.12308458, 0.03248905,
       0.12017393, 0.11276605])

In [18]:
lr.best_fit

array([12.18164898,  0.28167966,  0.03693591,  0.1494704 ,  0.0743033 ,
        0.1141373 ,  0.08338239,  0.10628964,  0.11864355,  0.12308458,
        0.03248905,  0.12017393,  0.11276605])

In [19]:
y_pred = lr.predict(x_test)

In [20]:
print(y_pred)

[15.63917815 15.21449309 15.65763942 15.14984661 15.20397264 15.62082586
 15.23848336 14.78787446 14.90382707 15.57952852 15.97650286 15.03016994
 15.70960238 15.09567505 15.01628492 14.7382563  15.85216399 15.47556577
 15.28289853 14.86507585 14.8970469  15.2196636  15.59597809 15.60644723
 15.1673896  15.05769405 15.63194996 15.34580435 15.39414014 15.25022131
 15.6382071  15.59633766 14.78860698 15.13816445 15.55838866 15.28325869
 15.34829014 15.70447362 15.71332761 15.26702655 15.19993438 15.02275689
 15.43068581 15.30485811 14.79991234 14.90313147 15.20093209 15.36146084
 15.3689805  15.57903234 15.01993043 15.06131536 14.84377242 15.69339524
 15.01925698 15.21491255 14.91590435 15.36111955 15.10029117 15.02485043
 15.29043708 15.17502216 15.04596209 15.09237233 15.19145257 14.99683781
 15.43115848 15.36860966 15.63269196 15.39926907 15.67707047 15.01589752
 15.5027144  15.56467534 15.2940474  15.34955644 15.66489513 15.57623253
 15.41973403 15.94253793 14.87207519 15.90520027 15.20408349 15.71224549
 15.0852496  15.22607797 15.19270078 15.24565914 15.67436509 14.93249968
 14.97810359 15.70320153 15.27714489 15.5999568  15.28178167 15.36629508
 15.18169154 15.68391357 15.4914312  14.78365572 14.99028937 15.32032104
 15.18620345 15.2904126  15.25328928 15.14510517 15.74503786 14.76498932
 15.38608495 14.73452538 15.26351171 14.90313147 15.27464507 14.96150271
 14.89942289 15.3480083  15.09245124 15.14955219 15.02084474 15.70793192
 15.36847779 15.19719775 15.20725029 15.79122173 15.54455327 15.3576043
 15.00267644 15.07379083 15.33449836 14.93871275 15.34293524 15.23832952
 15.12775735 15.72393889 15.17157367 15.61324485 15.01514347 15.54942244
 15.19320064 14.88911099 15.27548742 15.64216644 14.88755698 16.07626754
 14.96872483 15.43775099 15.53030301 15.24187267 15.7696678  15.39071975
 15.72156403 15.55666339 15.48749418 15.40912675 15.16236818 15.49678066
 15.43504804 15.70211692 15.67186824 15.28157356 15.50865278 15.24469288
 15.56178551 14.9909847  15.56414967 15.65993807 15.02301581 15.10718168
 15.57519902 15.28679454 14.87553501 15.13317931 15.40890875 15.47226247
 15.47687222 15.47420492 15.21648879 15.59162077 15.06778302 15.00343862
 15.6139857  15.22383715 15.3407771  15.42010769 15.59443789 15.2637912
 14.83034966 15.75849994 15.44128318 14.8920838  15.82566208 15.62164498
 15.5152981  14.71210547 15.51033196 15.84188234 15.74783338 14.88115173
 15.28968023 15.65326153 15.06373714 15.5594979  15.18994453 15.54445724
 15.47433486 15.11276644 15.17264933 14.94845359 15.22330261 15.24305579
 14.98091931 15.07656786]

In [21]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [22]:
mae = mean_absolute_error(y_test,y_pred)
print("MAE : ",mae);
mse = mean_squared_error(y_test,y_pred)
print("MSE : ",mse)
rmse = np.sqrt(mse)
print("RMSE : ",rmse)
r2 = r2_score(y_test,y_pred)
print("R2 :",r2)

MAE :  0.17970908981162528
MSE :  0.05366758769142958
RMSE :  0.23166265925139853
R2 : 0.6305925478239427

In [23]:
# linear regression using sklearn linear model

In [26]:
from sklearn.linear_model import LinearRegression

In [27]:
linear_regression = LinearRegression()

In [28]:
linear_regression.fit(x_train,y_train)

LinearRegression()

In [29]:
y_predicted = linear_regression.predict(x_test)

In [30]:
print(y_predicted)

[15.63917815 15.21449309 15.65763942 15.14984661 15.20397264 15.62082586
 15.23848336 14.78787446 14.90382707 15.57952852 15.97650286 15.03016994
 15.70960238 15.09567505 15.01628492 14.7382563  15.85216399 15.47556577
 15.28289853 14.86507585 14.8970469  15.2196636  15.59597809 15.60644723
 15.1673896  15.05769405 15.63194996 15.34580435 15.39414014 15.25022131
 15.6382071  15.59633766 14.78860698 15.13816445 15.55838866 15.28325869
 15.34829014 15.70447362 15.71332761 15.26702655 15.19993438 15.02275689
 15.43068581 15.30485811 14.79991234 14.90313147 15.20093209 15.36146084
 15.3689805  15.57903234 15.01993043 15.06131536 14.84377242 15.69339524
 15.01925698 15.21491255 14.91590435 15.36111955 15.10029117 15.02485043
 15.29043708 15.17502216 15.04596209 15.09237233 15.19145257 14.99683781
 15.43115848 15.36860966 15.63269196 15.39926907 15.67707047 15.01589752
 15.5027144  15.56467534 15.2940474  15.34955644 15.66489513 15.57623253
 15.41973403 15.94253793 14.87207519 15.90520027 15.20408349 15.71224549
 15.0852496  15.22607797 15.19270078 15.24565914 15.67436509 14.93249968
 14.97810359 15.70320153 15.27714489 15.5999568  15.28178167 15.36629508
 15.18169154 15.68391357 15.4914312  14.78365572 14.99028937 15.32032104
 15.18620345 15.2904126  15.25328928 15.14510517 15.74503786 14.76498932
 15.38608495 14.73452538 15.26351171 14.90313147 15.27464507 14.96150271
 14.89942289 15.3480083  15.09245124 15.14955219 15.02084474 15.70793192
 15.36847779 15.19719775 15.20725029 15.79122173 15.54455327 15.3576043
 15.00267644 15.07379083 15.33449836 14.93871275 15.34293524 15.23832952
 15.12775735 15.72393889 15.17157367 15.61324485 15.01514347 15.54942244
 15.19320064 14.88911099 15.27548742 15.64216644 14.88755698 16.07626754
 14.96872483 15.43775099 15.53030301 15.24187267 15.7696678  15.39071975
 15.72156403 15.55666339 15.48749418 15.40912675 15.16236818 15.49678066
 15.43504804 15.70211692 15.67186824 15.28157356 15.50865278 15.24469288
 15.56178551 14.9909847  15.56414967 15.65993807 15.02301581 15.10718168
 15.57519902 15.28679454 14.87553501 15.13317931 15.40890875 15.47226247
 15.47687222 15.47420492 15.21648879 15.59162077 15.06778302 15.00343862
 15.6139857  15.22383715 15.3407771  15.42010769 15.59443789 15.2637912
 14.83034966 15.75849994 15.44128318 14.8920838  15.82566208 15.62164498
 15.5152981  14.71210547 15.51033196 15.84188234 15.74783338 14.88115173
 15.28968023 15.65326153 15.06373714 15.5594979  15.18994453 15.54445724
 15.47433486 15.11276644 15.17264933 14.94845359 15.22330261 15.24305579
 14.98091931 15.07656786]

In [31]:
print(linear_regression.intercept_)
print(linear_regression.coef_)

12.181648980430555
[0.28167966 0.03693591 0.1494704  0.0743033  0.1141373  0.08338239
 0.10628964 0.11864355 0.12308458 0.03248905 0.12017393 0.11276605]

In [32]:
mae = mean_absolute_error(y_test,y_predicted)
print("MAE : ",mae);
mse = mean_squared_error(y_test,y_predicted)
print("MSE : ",mse)
rmse = np.sqrt(mse)
print("RMSE : ",rmse)
r2 = r2_score(y_test,y_predicted)
print("R2 :",r2)

MAE :  0.17970908981167744
MSE :  0.053667587691415726
RMSE :  0.2316626592513686
R2 : 0.6305925478240382